name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build Package
        run: python -m build
      - name: Test Build
        env:
          SESSDATA: "mock_sessdata_for_testing"
        run: |
          python -m pip install dist/*.whl
          python -c "import bilibili_video_info_mcp; import bilibili_video_info_mcp.bilibili_api; import bilibili_video_info_mcp.server"
